// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQDBG36mNM792lTKpLtzrm722uvuGGKo',
    appId: '1:15494962376:web:1f6cd6e59b8a221af999fd',
    messagingSenderId: '15494962376',
    projectId: 'deepnotes-flutter-2025',
    authDomain: 'deepnotes-flutter-2025.firebaseapp.com',
    storageBucket: 'deepnotes-flutter-2025.firebasestorage.app',
    measurementId: 'G-8EV495Q0S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWnUVOsH1QYyj2lk9JCBmNJy2u9QMzfsg',
    appId: '1:15494962376:android:c486b57c0642d2aff999fd',
    messagingSenderId: '15494962376',
    projectId: 'deepnotes-flutter-2025',
    storageBucket: 'deepnotes-flutter-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIC-BlM-pcjIiE1keFIKcEZEP-rwmvWYI',
    appId: '1:15494962376:ios:3b94273c49fd9c16f999fd',
    messagingSenderId: '15494962376',
    projectId: 'deepnotes-flutter-2025',
    storageBucket: 'deepnotes-flutter-2025.firebasestorage.app',
    iosClientId: '15494962376-fonii25em0ni1rc64r5nriec0auig9h8.apps.googleusercontent.com',
    iosBundleId: 'com.vikram.deepnotesflutter.deepnotesFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIC-BlM-pcjIiE1keFIKcEZEP-rwmvWYI',
    appId: '1:15494962376:ios:3b94273c49fd9c16f999fd',
    messagingSenderId: '15494962376',
    projectId: 'deepnotes-flutter-2025',
    storageBucket: 'deepnotes-flutter-2025.firebasestorage.app',
    iosClientId: '15494962376-fonii25em0ni1rc64r5nriec0auig9h8.apps.googleusercontent.com',
    iosBundleId: 'com.vikram.deepnotesflutter.deepnotesFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkQDBG36mNM792lTKpLtzrm722uvuGGKo',
    appId: '1:15494962376:web:93f63af589ec4696f999fd',
    messagingSenderId: '15494962376',
    projectId: 'deepnotes-flutter-2025',
    authDomain: 'deepnotes-flutter-2025.firebaseapp.com',
    storageBucket: 'deepnotes-flutter-2025.firebasestorage.app',
    measurementId: 'G-35K9ZDPH7P',
  );

}