name: deepnotes_flutter
description: "A notes taking app built with Flutter and Material Design 3."

publish_to: "none" # Prevent accidental publishing to pub.dev

# Versioning
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.0.0

  # Local storage
  sqflite: ^2.2.8+1
  path: ^1.8.3
  shared_preferences: ^2.2.2

  # Utilities
  flutter_launcher_icons: ^0.14.4
  package_info_plus: ^8.3.1
  url_launcher: ^6.3.2
  share_plus: ^11.1.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Launcher icons config
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/deepnotes.png"

flutter:
  uses-material-design: true

  # App assets
  assets:
    - assets/icons/deepnotes.png
